-- better-auth core tables (email/password). Created in the public schema.
-- IDs are text holding a UUID string (generated by better-auth via
-- advanced.database.generateId = crypto.randomUUID) so they mirror 1:1 into
-- auth.users.id (uuid). The ~30 public FKs continue to reference auth.users —
-- a signup hook keeps a thin auth.users row in sync. See MIGRATION-HANDOFF.md.

CREATE TABLE IF NOT EXISTS public."user" (
  id            text PRIMARY KEY,
  name          text NOT NULL DEFAULT '',
  email         text NOT NULL UNIQUE,
  email_verified boolean NOT NULL DEFAULT false,
  image         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."session" (
  id          text PRIMARY KEY,
  expires_at  timestamptz NOT NULL,
  token       text NOT NULL UNIQUE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  ip_address  text,
  user_agent  text,
  user_id     text NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS session_user_id_idx ON public."session"(user_id);
CREATE INDEX IF NOT EXISTS session_token_idx ON public."session"(token);

CREATE TABLE IF NOT EXISTS public."account" (
  id                       text PRIMARY KEY,
  account_id               text NOT NULL,
  provider_id              text NOT NULL,
  user_id                  text NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  access_token             text,
  refresh_token            text,
  id_token                 text,
  access_token_expires_at  timestamptz,
  refresh_token_expires_at timestamptz,
  scope                    text,
  password                 text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS account_user_id_idx ON public."account"(user_id);

CREATE TABLE IF NOT EXISTS public."verification" (
  id          text PRIMARY KEY,
  identifier  text NOT NULL,
  value       text NOT NULL,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON public."verification"(identifier);
